version: '3.7'
networks:
    sannitas:
        driver: bridge
services:
    web:
        build: "/sannitas-web"
        container_name: sannitas-web
        restart: always
        networks:
            - sannitas
        ports:
            - "80:3000"
        depends_on:
            - crud-usuarios
            - crud-empresas
    crud-usuarios:
      build: "/CRUD-Usuario"
      container_name: crud-usuarios
      networks:
        - sannitas
      restart: always
      ports:
        - "8001:8080"
    crud-empresas:
        build: "/Servico-empresa"
        container_name: crud-empresas
        networks:
            - sannitas
        restart: always
        ports:
            - "8002:8080"
        