# Use a imagem oficial do MySQL como base
FROM mysql:latest

# Defina variáveis de ambiente para configurar o MySQL
ENV MYSQL_DATABASE=sanittas
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

EXPOSE 3306
